name: Run MicroPython Tests

on:
  push:
    branches:
      - '**' # Trigger on any branch push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install micropython
        uses: BrianPugh/install-micropython@v2
        with:
          referenc: v1.23.0

      - name: Install unittest
        run: |
          micropython -m mip install unittest

      - name: Install deps
        run: |
          deps=$(jq -r '.deps[] | "\(.[0])@\(.[1])"' package.json)
          echo "$deps" | xargs -I {} micropython -m mip install {}

      - name: Run tests
        run: |
          micropython test.py