name: Run MicroPython Tests

on:
  push:
    branches:
      - '**' # Trigger on any branch push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t micropython-unix-rp2-tests .

      # Install unittest, mounting the volume locally
      - name: Install unittest via MIP
        run: |
          docker run --rm -v $(pwd)/lib:/root/.micropython/lib micropython-unix-rp2-tests micropython -m mip install unittest

      - name: Run tests
        run: |
          docker run --rm -v $(pwd):/code -v $(pwd)/lib:/root/.micropython/lib micropython-unix-rp2-tests micropython test.py
